version: '3'

services:
# MySql Database used for Prisma as main
  main-database:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: helloworld
    ports:
      - "3308:3306"

# MySql Database used for Prisma as shadow
  shadow-database:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: shadow
      MYSQL_ROOT_PASSWORD: helloworld
    ports:
      - "3309:3306"

# Adminer UI 
  adminer:
    image: adminer:4.5.0
    ports:
      - "9090:8080"